version: "0"
services:
    monapp:
        image: flask
        container_name: monapp
        ports:
            - 5000:5000
        volumes:
            - ./pythonproject1/text.txt:/pythonproject1/text.txt
    mongo-container:
        container_name: mongo-container
        image: mongo
        volumes:
            - mon-volume:/data/db

volumes:
    mon-volume: